/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arqma_arqnet_ArqnetVPN */

#ifndef _Included_com_arqma_arqnet_ArqnetVPN
#define _Included_com_arqma_arqnet_ArqnetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_PacketSize(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_Alloc(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_Stop(JNIEnv *, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_ReadPkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_WritePkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetVPN
   * Method:    SetInfo
   * Signature: (Lcom/arqma/arqnet/ArqnetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_ArqnetVPN_SetInfo(JNIEnv *, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
