/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arqma_arqnet_ArqnetConfig */

#ifndef _Included_com_arqma_arqnet_ArqnetConfig
#define _Included_com_arqma_arqnet_ArqnetConfig
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     com_arqma_arqnet_ArqnetConfig
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_com_arqma_arqnet_ArqnetConfig_Obtain(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_ArqnetConfig
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_ArqnetConfig_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetConfig
   * Method:    Load
   * Signature: (Ljava/lang/String;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetConfig_Load(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
