/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arqma_arqnet_ArqnetVPN_VPNInfo */

#ifndef _Included_com_arqma_arqnet_ArqnetVPN_VPNInfo
#define _Included_com_arqma_arqnet_ArqnetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
