/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arqma_arqnet_Arqnet_JNI */

#ifndef _Included_com_arqma_arqnet_Arqnet_JNI
#define _Included_com_arqma_arqnet_Arqnet_JNI
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     com_arqma_arqnet_Arqnet_JNI
   * Method:    getABICompiledWith
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_getABICompiledWith(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_Arqnet_JNI
   * Method:    startArqnet
   * Signature: (Ljava/lang/String;)Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_startArqnet(JNIEnv *, jclass,
                                                      jstring);

  JNIEXPORT jstring JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_getIfAddr(JNIEnv *, jclass);

  JNIEXPORT jint JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_getIfRange(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_Arqnet_JNI
   * Method:    stopArqnet
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_stopArqnet(JNIEnv *, jclass);

  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_setVPNFileDescriptor(JNIEnv *, jclass,
                                                              jint, jint);

  /*
   * Class:     com_arqma_arqnet_Arqnet_JNI
   * Method:    onNetworkStateChanged
   * Signature: (Z)V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_Arqnet_1JNI_onNetworkStateChanged(JNIEnv *, jclass,
                                                               jboolean);

#ifdef __cplusplus
}
#endif
#endif
