/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arqma_arqnet_ArqnetDaemon */

#ifndef _Included_com_arqma_arqnet_ArqnetDaemon
#define _Included_com_arqma_arqnet_ArqnetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_Obtain(JNIEnv *, jclass);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    Configure
   * Signature: (Lcom/arqma/arqnet/ArqnetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_Configure(JNIEnv *, jobject, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_Mainloop(JNIEnv *, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_IsRunning(JNIEnv *, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_Stop(JNIEnv *, jobject);

  /*
   * Class:     com_arqma_arqnet_ArqnetDaemon
   * Method:    InjectVPN
   * Signature: (Lcom/arqma/arqnet/ArqnetVPN;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_com_arqma_arqnet_ArqnetDaemon_InjectVPN(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
