#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/arqnet || echo "failed to setcap arqnet"
adduser --quiet --system --home /var/lib/arqnet debian-arqnet || echo "debian-arqnet user not added"
