#!/bin/sh

PERMS_OWNER=root
PERMS_GROUP=admin
CHOWN=$PERMS_OWNER:$PERMS_GROUP

# set up arqnet data dir
[ -e /var/lib/arqnet/ ] || mkdir /var/lib/arqnet
chown $CHOWN /var/lib/arqnet
chmod g+w /var/lib/arqnet

# mv files copied into $INSTALL_PREFIX/extra/ to their proper locations
mv /opt/arqnet/extra/arqnet_macos_daemon_script.sh /var/lib/arqnet
chown $CHOWN /var/lib/arqnet/arqnet_macos_daemon_script.sh
chmod 770 /var/lib/arqnet/arqnet_macos_daemon_script.sh

mv /opt/arqnet/extra/com.arqma.arqnet.daemon.plist /Library/LaunchDaemons/
chown $CHOWN /Library/LaunchDaemons/com.arqma.arqnet.daemon.plist
chmod 640 /Library/LaunchDaemons/com.arqma.arqnet.daemon.plist

# clean up by removing 'extra/' (so long as it's empty)
rmdir /opt/arqnet/extra/

# bootstrap
/opt/arqnet/bin/arqnet-bootstrap mainnet /var/lib/arqnet/bootstrap.signed
chown $CHOWN /var/lib/arqnet/bootstrap.signed

# generate configs
/opt/arqnet/bin/arqnet -g /var/lib/arqnet/arqnet.ini
chown $CHOWN /var/lib/arqnet/arqnet.ini

# register with launchd and start
launchctl load /Library/LaunchDaemons/com.arqma.arqnet.daemon.plist
launchctl start com.arqma.arqnet.daemon
