name: Build Arq-Net Linux & Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: [ubuntu-22.04, ubuntu-24.04]
    name: Linux build (${{ matrix.ubuntu }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: 'recursive'

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libcap-dev curl libuv1-dev libsodium-dev libcurl4-openssl-dev pkg-config libsystemd-dev

      - name: Build (make)
        run: make

  static-linux-build:
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: [ubuntu-22.04, ubuntu-24.04]
    name: Static Linux build (${{ matrix.ubuntu }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: 'recursive'

      - name: Install dependencies (Static Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libcap-dev curl libuv1-dev libsodium-dev libcurl4-openssl-dev pkg-config

      - name: Clean build directory
        run: rm -rf build/

      - name: Static Build (CMake, bez systemd)
        run: |
          cmake -S . -B build -DWITH_SYSTEMD=OFF -DSTATIC_LINK=ON
          cmake --build build --target arqnet-static

  windows-build:
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: [ubuntu-22.04, ubuntu-24.04]
    name: Windows cross-build (${{ matrix.ubuntu }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: 'recursive'

      - name: Install dependencies (Windows cross-compile)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config pkg-config-mingw-w64 mingw-w64 nsis autoconf automake libtool

      - name: Build libsodium for MinGW
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
          tar xzf libsodium-1.0.18.tar.gz
          cd libsodium-1.0.18
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export AR=x86_64-w64-mingw32-ar
          export RANLIB=x86_64-w64-mingw32-ranlib
          export STRIP=x86_64-w64-mingw32-strip
          export LD=x86_64-w64-mingw32-ld
          ./configure --host=x86_64-w64-mingw32 --prefix=$HOME/mingw-libsodium --disable-shared --enable-static
          make -j$(nproc)
          make install

      - name: Build libcurl for MinGW (no SSL)
        run: |
          wget https://curl.se/download/curl-7.82.0.tar.gz
          tar xzf curl-7.82.0.tar.gz
          cd curl-7.82.0
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export AR=x86_64-w64-mingw32-ar
          export RANLIB=x86_64-w64-mingw32-ranlib
          export STRIP=x86_64-w64-mingw32-strip
          export LD=x86_64-w64-mingw32-ld
          PKG_CONFIG_PATH="$HOME/mingw-libsodium/lib/pkgconfig"
          ./buildconf
          ./configure --host=x86_64-w64-mingw32 --prefix=$HOME/mingw-libcurl --with-sodium=$HOME/mingw-libsodium --disable-shared --enable-static --without-ssl
          make -j$(nproc)
          make install

      - name: Build for Windows (make windows-release)
        env:
          PKG_CONFIG_PATH: $HOME/mingw-libsodium/lib/pkgconfig:$HOME/mingw-libcurl/lib/pkgconfig
          PKG_CONFIG: x86_64-w64-mingw32-pkg-config
          LIBSODIUM_ROOT: $HOME/mingw-libsodium
          LIBCURL_ROOT: $HOME/mingw-libcurl
        run: make windows-release
